CollectiveVotingBundle\Entity\Vote:
    type: entity
    repositoryClass: CollectiveVotingBundle\Repository\VoteRepository
    table: cv_vote
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        dateAdded:
            column: date_added
            type: datetimetz
            nullable: false

        voteOption:
            column: vote_option
            type: string
            length: 24
            nullable: false
        valid:
            column: is_valid
            type: boolean
            options:
                default: 1



    manyToOne:
        votingProcess:
            targetEntity: CollectiveVotingBundle\Model\Entity\VotingProcessInterface
            inversedBy: votes
            joinColumn:
                name: voting_process_id
                referencedColumnName: id

        voter:
            targetEntity: CollectiveVotingBundle\Model\Entity\VotingParticipantInterface
            joinColumn:
                name: voting_user_id
                referencedColumnName: id


