CollectiveVotingBundle\Entity\VotingProcess:
    type: entity
    repositoryClass: CollectiveVotingBundle\Repository\VotingProcessRepository
    table: cv_voting_process
    uniqueConstraints:
        vp_idx:
            columns: subject_type,subject_id

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        subjectType:
            column: subject_type
            type: string
            length: 24
            nullable: false

        dateAdded:
            column: date_added
            type: datetimetz
            nullable: false

        subjectId:
            column: subject_id
            type: string
            length: 24
            nullable: false

        state:
            column: state
            type: string
            length: 16
            options:
                default: "open"

        decisionStrategyName:
            column: decision_strategy_name
            type: string
            length: 32
            nullable: true
            options:
                default: ""

    oneToMany:
        votes:
            targetEntity: CollectiveVotingBundle\Entity\Vote
            mappedBy: votingProcess
            cascade: ["persist"]

    manyToOne:
        startedByUser:
            targetEntity: CollectiveVotingBundle\Model\Entity\VotingParticipantInterface
            joinColumn:
                name: process_started_by_id
                referencedColumnName: id