CollectiveVotingBundle\Entity\VotingProcess:
    type: entity
    repositoryClass: CollectiveVotingBundle\Repository\VotingProcessRepository
    table: cv_voting_process
    uniqueConstraints:
        vp_idx:
            columns: subject_type,subject_id

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        subjectType:
            column: subject_type
            type: string
            length: 24
            nullable: false

        dateAdded:
            column: date_added
            type: datetimetz
            nullable: false

        subjectId:
            column: subject_id
            type: string
            length: 24
            nullable: false

        state:
            column: state
            type: string
            length: 16
            options:
                default: "open"

    oneToMany:
        votes:
            targetEntity: CollectiveVotingBundle\Entity\Vote
            mappedBy: votingProcess

    manyToOne:
        startedByUser:
            targetEntity: Wolnosciowiec\AppBundle\Model\Entity\User
            joinColumn:
                name: process_started_by_id
                referencedColumnName: id