services:
    #
    # Decision maker
    #
    collectivevoting.decision_maker:
        class: CollectiveVotingBundle\DecisionMaker\DecisionMaker
        arguments:
            em: "@doctrine.orm.entity_manager"
            factory: "@collectivevoting.factory"
            container: "@service_container"
            serializer: "@serializer"


    #
    # Decision strategy: minimum
    #
    collectivevoting.strategy.minimum:
        class: CollectiveVotingBundle\DecisionMaker\Strategy\MinimumVotesStrategy